# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Statement', models.CharField(max_length=250)),
                ('Difficulty', models.CharField(max_length=2)),
                ('Input_Format', models.CharField(max_length=50)),
                ('Input_Constraints', models.CharField(max_length=50)),
                ('Input_Sample', models.CharField(max_length=50)),
                ('Ouput_Format', models.CharField(max_length=50)),
                ('Ouput_Constraints', models.CharField(max_length=50)),
                ('Ouput_Sample', models.CharField(max_length=50)),
                ('Memory_limit', models.IntegerField()),
                ('Time_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('language', models.CharField(max_length=5)),
                ('score', models.IntegerField()),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.UserProfile'),
        ),
        migrations.AddField(
            model_name='questions',
            name='Tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.Testcase'),
        ),
    ]
