# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.CategoriesQ')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Statement', models.FileField(upload_to='')),
                ('Difficulty', models.CharField(max_length=10)),
                ('Memory_limit', models.IntegerField()),
                ('Time_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('language', models.CharField(max_length=5)),
                ('score', models.CharField(blank=True, max_length=25)),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputTestFile', models.FileField(upload_to='')),
                ('outputTestFile', models.FileField(upload_to='')),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.Questions')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='submission',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.UserProfile'),
        ),
        migrations.AddField(
            model_name='ins',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.Questions'),
        ),
    ]
