# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesQ',
            fields=[
                ('Name', models.CharField(max_length=255)),
                ('Noq', models.IntegerField(default=0)),
                ('Cid', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.CategoriesQ')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avs.Questions')),
            ],
        ),
    ]
