# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0002_categoriesq_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesq',
            name='Cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
